SELECT O.YEAR AS YEAR, O.MONTH AS MONTH, U.GENDER, SUM(O.COUNT) AS USERS
FROM USER_INFO U, (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID, COUNT(DISTINCT USER_ID) AS COUNT
                   FROM ONLINE_SALE
                   GROUP BY YEAR, MONTH, USER_ID) O
WHERE U.USER_ID = O.USER_ID AND U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;