-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME_TABLE WHERE HOUR<23
)

SELECT T.HOUR,
    CASE
    WHEN A.COUNT IS NULL THEN 0
    ELSE COUNT
    END AS COUNT
FROM TIME_TABLE T LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
                    FROM ANIMAL_OUTS
                    GROUP BY HOUR) A ON T.HOUR = A.HOUR
ORDER BY HOUR;