-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, S.TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER U JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL
                             FROM USED_GOODS_BOARD
                             WHERE STATUS='DONE'
                             GROUP BY WRITER_ID
                             HAVING TOTAL>=700000) S ON U.USER_ID=S.WRITER_ID
ORDER BY TOTAL_SALES;