-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B, (SELECT BOOK_ID, SUM(SALES) AS SALES, SALES_DATE
              FROM BOOK_SALES
              WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
              GROUP BY BOOK_ID) S
WHERE B.BOOK_ID = S.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY;