-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(B.PRICE*BS.SALES) AS TOTAL_SALES
FROM AUTHOR A, BOOK B, (SELECT BOOK_ID, SUM(SALES) AS SALES
                        FROM BOOK_SALES
                        WHERE YEAR(SALES_DATE) = 2022 AND
                        MONTH(SALES_DATE) = 1
                        GROUP BY BOOK_ID) BS
WHERE B.BOOK_ID = BS.BOOK_ID AND A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;