-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, P.PRICE*O.CNT AS SALES
FROM PRODUCT P RIGHT JOIN 
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS CNT
     FROM OFFLINE_SALE
     GROUP BY PRODUCT_ID) O ON P.PRODUCT_ID=O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE;