SELECT DISTINCT H.HISTORY_ID, 
    CASE
    WHEN H.DIFF<7 THEN H.DIFF*H.FEE
    WHEN H.DIFF BETWEEN 7 AND 29 THEN ROUND(H.DIFF*H.FEE*(100-(SELECT D.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D WHERE DURATION_TYPE='7일 이상' AND CAR_TYPE = '트럭'))/100)
    WHEN H.DIFF BETWEEN 30 AND 89 THEN ROUND(H.DIFF*H.FEE*(100-(SELECT D.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D WHERE DURATION_TYPE='30일 이상' AND CAR_TYPE = '트럭'))/100)
    ELSE ROUND(H.DIFF*H.FEE*(100-(SELECT D.DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D WHERE DURATION_TYPE='90일 이상' AND CAR_TYPE = '트럭'))/100)
    END AS FEE
FROM (SELECT H.HISTORY_ID, H.CAR_ID, DATEDIFF(END_DATE,START_DATE)+1 AS DIFF, C.DAILY_FEE AS FEE
                                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID=C.CAR_ID AND C.CAR_TYPE='트럭') AS H
ORDER BY FEE DESC, HISTORY_ID DESC;