-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P, DOCTOR D, (SELECT APNT_NO, PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
                           FROM APPOINTMENT
                           WHERE APNT_CNCL_YN = 'N' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13') A
WHERE P.PT_NO=A.PT_NO AND D.DR_ID=A.MDDR_ID
ORDER BY A.APNT_YMD