-- 코드를 입력하세요
SELECT DISTINCT R.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR R RIGHT JOIN (SELECT CAR_ID
                                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                      WHERE MONTH(START_DATE)=10) H ON R.CAR_ID=H.CAR_ID
WHERE R.CAR_TYPE='세단'
ORDER BY R.CAR_ID DESC;